FROM mcr.microsoft.com/dotnet/runtime:3.1
COPY bin/Release/netcoreapp3.1/publish/ BOTone/
WORKDIR /BOTone
ENTRYPOINT ["dotnet", "BOTone.dll"]
ENV token=NzkwODUyNjgzNzY2MTY5NjEx.X-Go9Q.Lqw1_kFCamICNhet6eznO67yE9w